### ISSUE TITLE
Docker compose YAML file is dead

### ISSUE THREAD

**Issue by hongbo-miao** [systemcraftsman/influxdb-kafka-demo#1]
Thanks for the tutorial, Aykut!

Just reported a dead link https://raw.githubusercontent.com/systemcraftsman/influxdb-kafka-demo/main/resources/docker-compose.yaml which is at https://www.influxdata.com/blog/getting-started-apache-kafka-influxdb/

<img width="977" alt="image" src="https://user-images.githubusercontent.com/3375461/195151227-bed8b9c6-4c55-41ed-9b4d-31d2ac4c646e.png">

**Comment by mabulgu** [comment]
Thanks for letting me know @Hongbo-Miao ! The link is fixed (by moving the file to directly under "resources")
